- src/main/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/Version.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/common/util/Deserializer/AuthorRecordDeserializer.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/common/util/Deserializer/ReviewRecordDeserializer.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/common/util/Deserializer/SubmissionRecordDeserializer.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/common/util/Deserializer/VersionDeserializer.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/common/util/Serializer/VersionSerializer.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/logic/RecordLogic.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/logic/VersionLogic.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/storage/repository/VersionRepository.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/VersionController.java
> Rename variable version and VersionPk for clarity

- src/main/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/RecordController.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/VersionController.java
> Add endpoint skeletons and todos

- src/main/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/AuthorRecord.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/ReviewRecord.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/SubmissionRecord.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/Version.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/common/util/Serializer/VersionSerializer.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/logic/RecordLogic.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/logic/VersionLogic.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/VersionController.java
Part of #32 by fixing the creation of `Version`. Trying to import any records however still cause an exception.
> Fix Version database mapping

- src/test/java/sg/edu/nus/comp/cs3219/viz/logic/GateKeeperTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/test/BaseTestCase.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/test/GaeSimulation.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/AuthInfoControllerTest.java
> Add GAE simulation for base test class

- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/VersionTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/logic/GateKeeperComponentTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/test/BaseComponentTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/AuthInfoControllerComponentTest.java
> Add VersionTest and BaseComponentTest

- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/ConferenceTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/PresentationAccessControlTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/PresentationSectionTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/PresentationTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/AuthorRecordTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/ReviewRecordTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/SubmissionAuthorRecordTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/SubmissionRecordTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/VersionTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/logic/GateKeeperTest.java
> Add entity test skeletons

- src/main/java/sg/edu/nus/comp/cs3219/viz/logic/AnalysisLogic.java
> Fixes presentation not loading due to naming changes

- src/test/java/sg/edu/nus/comp/cs3219/viz/logic/GateKeeperTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/test/BaseComponentTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/test/FileHelper.java
> Add GateKeeperTest

- src/web/app/src/components/SectionListPanel.vue
- src/web/app/src/store/index.js
- src/web/app/src/store/modules/data.js
- src/web/app/src/store/modules/dataManage.js
- src/web/app/src/store/modules/presentation.js
- src/web/app/src/views/ImportData.vue
- src/web/app/src/views/ManageData.vue
> Setup dataManage.js

- src/web/app/src/components/SectionListPanel.vue
- src/web/app/src/store/index.js
- src/web/app/src/store/modules/data.js
- src/web/app/src/store/modules/dataManage.js
- src/web/app/src/store/modules/presentation.js
- src/web/app/src/views/ImportData.vue
- src/web/app/src/views/ManageData.vue
> Add MyDataPage UI

- src/web/app/src/components/AbstractSectionDetail.vue
- src/web/app/src/components/PresentationBrief.vue
- src/web/app/src/components/SectionListPanel.vue
- src/web/app/src/components/emptyStates/EmptyPresentation.vue
- src/web/app/src/store/data/predefinedQueries.js
- src/web/app/src/store/data/requiredDataSets.js
- src/web/app/src/views/Analyze.vue
- src/web/app/src/views/NewPresentation.vue
- src/web/app/src/views/PresentationSection.vue
Fixes #28
- Improved UI of "My Presentations" and "Presentation Details" page
- Changed version to data set
- Enforced setting data set for new presentations
- Added confirmation for deleting presentations
- Added file type tags after data sets
- Show only available options for the "add section" drop down
> Improve presentations page

- src/main/java/sg/edu/nus/comp/cs3219/viz/logic/RecordLogic.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/RecordController.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/VersionController.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/AuthorRecordTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/ReviewRecordTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/SubmissionAuthorRecordTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/SubmissionRecordTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/record/VersionTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/logic/GateKeeperTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/test/BaseComponentTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/test/FileHelper.java
- src/web/app/src/components/AbstractSectionDetail.vue
- src/web/app/src/components/PresentationBrief.vue
- src/web/app/src/components/SectionListPanel.vue
- src/web/app/src/components/emptyStates/EmptyPresentation.vue
- src/web/app/src/store/data/predefinedQueries.js
- src/web/app/src/store/data/requiredDataSets.js
- src/web/app/src/store/index.js
- src/web/app/src/store/modules/data.js
- src/web/app/src/store/modules/dataManage.js
- src/web/app/src/store/modules/presentation.js
- src/web/app/src/views/Analyze.vue
- src/web/app/src/views/ImportData.vue
- src/web/app/src/views/ManageData.vue
- src/web/app/src/views/NewPresentation.vue
- src/web/app/src/views/PresentationSection.vue
Initial API implementation. Will flesh out and implement logic in the afternoon (going for 2 hours errand now)
> [WIP] Initial Record API.

- src/main/java/sg/edu/nus/comp/cs3219/viz/logic/VersionLogic.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/RecordController.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/VersionController.java
Fixes #
-
-
-
A few sentences describing the overall goals of the pull request's commits.
Add screenshots to [summarize the UI changes (if any)]
> Version APIs

- src/web/app/src/store/modules/dataManage.js
- src/web/app/src/views/ManageData.vue
> Add API request calls to dataManage.js

- src/main/java/sg/edu/nus/comp/cs3219/viz/storage/repository/AuthorRecordRepository.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/storage/repository/ConferenceRepository.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/storage/repository/PresentationAccessControlRepository.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/storage/repository/PresentationRepository.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/storage/repository/PresentationSectionRepository.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/storage/repository/ReviewRecordRepository.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/storage/repository/SubmissionAuthorRecordRepository.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/storage/repository/SubmissionRecordRepository.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/storage/repository/VersionRepository.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/logic/GateKeeperTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/logic/VersionLogicTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/VersionControllerTest.java
> Add test skeletons

- src/web/app/src/common/utility.js
- src/web/app/src/components/MappingTool.vue
- src/web/app/src/store/modules/dataMapping.js
- src/web/app/src/store/modules/fileParser.js
- src/web/app/src/views/ImportData.vue
Fixes #48 
Refactor file importing and parsing logic to use a dynamic, row based approach.
-
-
> Add support for SoftConf and other data formats

- src/main/java/sg/edu/nus/comp/cs3219/viz/logic/VersionLogic.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/VersionController.java
Fixes #
-
-
-
A few sentences describing the overall goals of the pull request's commits.
Add screenshots to [summarize the UI changes (if any)]
> Fix import data bug.

- .gitignore
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/ConferenceTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/PresentationAccessControlTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/PresentationSectionTest.java
- src/test/java/sg/edu/nus/comp/cs3219/viz/common/entity/PresentationTest.java
> Add entity tests

- .gitignore
- src/web/app/src/views/ImportData.vue
- src/web/app/src/views/ManageData.vue
Fixes #49 
Resolves #3 
@niqiukun @alyip98 I can't seem to get the individual record to upload, the http request is never sent. Can y'all help me take a look if I'm doing it right?
> Add upload functionality to My Data page

- .travis.yml
- src/web/app/package.json
- src/web/app/src/__tests__/__snapshots__/FeatureListDetail.vue.test.js.snap
- src/web/app/src/components/homePageDetail/FeatureListDetail.vue
- src/web/app/src/views/ImportData.vue
- src/web/app/src/views/ManageData.vue
- Front page now points to data page
- Move to data page after import
- Remove frontend from coveralls (Resolves #22)
> Change start flow to use data page

- src/main/java/sg/edu/nus/comp/cs3219/viz/logic/VersionLogic.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/VersionController.java
- src/web/app/src/store/modules/dataManage.js
> Fix data deletion process

- src/web/app/src/store/modules/dataManage.js
- src/web/app/src/views/ManageData.vue
> Update put request body key

- src/main/java/sg/edu/nus/comp/cs3219/viz/logic/RecordLogic.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/logic/VersionLogic.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/RecordController.java
- src/main/java/sg/edu/nus/comp/cs3219/viz/ui/controller/api/VersionController.java
Fixes #
-
-
-
A few sentences describing the overall goals of the pull request's commits.
Add screenshots to [summarize the UI changes (if any)]
> Fix all data deletion.

- src/web/app/src/store/modules/dataManage.js
> Change update version API call sequence

- src/web/app/src/store/modules/dataManage.js
- src/web/app/src/views/ImportData.vue
- src/web/app/src/views/ManageData.vue
> Change edit version request body

- src/main/java/sg/edu/nus/comp/cs3219/viz/logic/RecordLogic.java
Fixes #
-
-
-
A few sentences describing the overall goals of the pull request's commits.
Add screenshots to [summarize the UI changes (if any)]
> Make edit work.

- src/web/app/src/components/PresentationBrief.vue
- src/web/app/src/components/SectionListPanel.vue
- src/web/app/src/store/modules/dataManage.js
- src/web/app/src/views/Analyze.vue
- src/web/app/src/views/ManageData.vue
- src/web/app/src/views/NewPresentation.vue
- src/web/app/src/views/PresentationSection.vue
Realised that it is better to use getters instead of passing by props while writing the report.
> Use Vuex store getters

- src/web/app/src/store/modules/fileParser.js
Makes the data transform result consistent with the original parsing logic.
Details:
> Fix easychair default data transform

- src/web/app/src/store/modules/fileParser.js
- src/web/app/src/views/ImportData.vue
- src/web/app/src/views/ManageData.vue
Maps more data columns to softconf for more available visualisations
> Fix softconf default data transforms
